# 텐서플로의 텐서 연산

이 절의 내용을 실행하려면 텐서플로우 2.0 버전을 임포트해야 한다.

In [1]:
import numpy as np
import tensorflow as tf

tf.__version__ # 텐서플로우 버전확인

'2.3.1'

Tensor 자료형의 연산은 TensorFlow가 제공하는 연산자를 사용해야 한다. 

### 기본 연산

다음과 같은 기본 연산은 특수 메서드를 이용하여 연산자 오버로딩이 되어 있으므로 그냥 연산자 기호를 사용해도 된다.

* `tf.add`: 덧셈
* `tf.subtract`: 뺄셈
* `tf.multiply`: 곱셈
* `tf.divide`: 나눗셈
* `tf.pow`: n-제곱
* `tf.negative`: 음수 부호


In [2]:
a = tf.range(6, dtype=tf.int32)      # [0, 1, 2, 3, 4, 5]
b = 2 * tf.ones(6, dtype=tf.int32)   # [2, 2, 2, 2, 2, 2]

tf.add(a, b).numpy()

array([2, 3, 4, 5, 6, 7])

In [3]:
(a + b).numpy()

array([2, 3, 4, 5, 6, 7])

In [4]:
(a - b).numpy()

array([-2, -1,  0,  1,  2,  3])

In [5]:
(a * b).numpy()

array([ 0,  2,  4,  6,  8, 10])

In [6]:
(a / b).numpy()

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [7]:
(a ** 2).numpy()

array([ 0,  1,  4,  9, 16, 25])

In [8]:
(-b).numpy()

array([-2, -2, -2, -2, -2, -2])


* `tf.abs`: 절대값
* `tf.sign`: 부호
* `tf.round`: 반올림
* `tf.ceil`: 올림
* `tf.floor`: 내림
* `tf.square`: 제곱
* `tf.sqrt`: 제곱근
* `tf.maximum`: 두 텐서의 각 원소에서 최댓값만 반환.
* `tf.minimum`: 두 텐서의 각 원소에서 최솟값만 반환.
* `tf.cumsum`: 누적합
* `tf.cumprod`: 누적곱


In [9]:
tf.maximum(a, b).numpy()

array([2, 2, 2, 3, 4, 5])

벡터나 행렬의 원소들을 연산하여 스칼라 값을 구하는 차원 축소 연산은 `tf.reduce_` 명령을 사용한다.

* `tf.reduce_all`: 설정한 축으로 이동하면서 `and`논리 연산을 수행한다. 
* `tf.reduce_any`: 설정한 축으로 이동하면서 `or`논리 연산을 수행한다. 
* `tf.reduce_mean`: 설정한 축의 평균을 구한다. 
* `tf.reduce_max`: 설정한 축의 최댓값을 구한다. 
* `tf.reduce_min`: 설정한 축의 최솟값을 구한다. 
* `tf.reduce_prod`: 설정한 축의 요소를 모두 곱한 값을 구한다. 
* `tf.reduce_sum`: 설정한 축의 요소를 모두 더한 값을 구한다. 
* `tf.reduce_logsumexp`: 설정한 축의 벡터가 $N$차원의 벡터 $x$라고 할 때 
$$ \log \left( \displaystyle\sum_{i=0}^N \exp x_i\right) $$


In [10]:
tf.reduce_sum(a).numpy()

15

In [11]:
x_arr = np.arange(18).reshape(3,2,3) # numpy array 생성
print("x_arr\n", x_arr)
x2 = tf.reshape(x_arr, shape=(-1,6)) # numpy array로 부터 텐서를 생성하고 shape 변경
print("\nx2\n",x2)

x_arr
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]

x2
 tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]], shape=(3, 6), dtype=int32)


In [12]:
# 각 열의 합을 계산
xsum = tf.reduce_sum(x2, axis=0)
# 각 열의 평균을 계산
xmean = tf.reduce_mean(x2, axis=0)

In [13]:
print('x_array 크기 : ', x_arr.shape)
print('크기 변형, x2: \n', x2.numpy())
print('열의 합 : ', xsum.numpy())
print('열의 평균 : ', xmean.numpy())

x_array 크기 :  (3, 2, 3)
크기 변형, x2: 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
열의 합 :  [18 21 24 27 30 33]
열의 평균 :  [ 6  7  8  9 10 11]


### 자동 형변환

TensorFlow 연산자에 NumPy 배열이 들어가면 자동으로 상수 텐서 자료형으로 형변환 되어 연산이 이루어진다.

In [14]:
a = np.ones((2, 3), dtype=np.float32)
b = tf.ones([3, 1], dtype=tf.float32)
tf.matmul(a, b).numpy()

array([[3.],
       [3.]], dtype=float32)

### 행렬 연산

또한 행렬과 관련된 연산에서도 NumPy와는 이름이 다르므로 주의한다.

* `tf.matmul`: 내적
* `tf.linalg.inv`: 역행렬


In [15]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
b = tf.constant([[1, 1], [1, 1]], dtype=tf.float32)
tf.matmul(a, b).numpy()

array([[2., 2.],
       [1., 1.]], dtype=float32)

In [16]:
a = tf.constant([[2, 0], [0, 1]], dtype=tf.float32)
tf.linalg.inv(a).numpy()

array([[0.5, 0. ],
       [0. , 1. ]], dtype=float32)